### ISSUE TITLE
[1.12.2] Wrong-sided code crash on dimension travel!

### ISSUE THREAD

**Issue by Tokeli** [MinecraftBoomMod/Minecraft-Boom#8]
Forge: 14.23.4.2760
Boom: 1.4.3
v10verlap: 4.2

I'm using the mod V10verlap to travel between dimensions at certain world heights, instead of nether portals. It doesn't look related due to the error, but figured I should mention.

Dimension travel is fine on SSP, but in multiplayer you're trying to load a GUI serverside:

```
 
java.lang.NoClassDefFoundError: net/minecraft/client/gui/Gui
    at soupbubbles.minecraftboom.handler.EntityEventHandler.onDimensionTravel(EntityEventHandler.java:29)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_285_EntityEventHandler_onDimensionTravel_EntityTravelToDimensionEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onTravelToDimension(ForgeHooks.java:1060)
    at de.v10lator.v10verlap.V10verlap.onTick(V10verlap.java:248)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1509_V10verlap_onTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.Gui
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 13 more
Caused by: java.lang.NullPointerException
```

Full crash: https://pastebin.com/WkK0BuXU

Even a non-player entity such as an item, triggering a dimension change causes the crash.

Disabling the new dimension-traveling screens on the server config fixes the crash.

Edit: I encountered additional exceptions that didn't even pop up as an error!
These were encountered on SSP: https://pastebin.com/9hRMQuYt

**Comment by Phrille** [comment]
Not relevant version 1.12.2 is now outdated
